# -*- coding: utf-8 -*-
"""Copy of Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzAgSNiwdH6FDtG_1t_YsKfQddZaG0IJ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])

df.head()

df.head()
df.info()
df.shape
df.describe()

df.isnull().sum()
(df.isnull().sum() / len(df)) * 100
df.duplicated().sum()
df = df.drop_duplicates()

df.dtypes

num_cols = df.select_dtypes(include=['float64', 'int64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.show()

for col in cat_cols[:10]:
    plt.figure(figsize=(6,4))
    sns.countplot(y=df[col])
    plt.title(f'Count of {col}')
    plt.show()

plt.figure(figsize=(14,8))
sns.heatmap(df[num_cols].corr(), annot=False, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

sns.pairplot(df[num_cols])
plt.show()

for col in cat_cols:
    for num in num_cols:
        plt.figure(figsize=(6,4))
        sns.boxplot(x=col, y=num, data=df)
        plt.title(f'{num} vs {col}')
        plt.xticks(rotation=45)
        plt.show()

for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(data=df, x=col)
    plt.title(f'Outliers in {col}')
    plt.show()

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < (Q1 - 1.5 * IQR)) | (df[col] > (Q3 + 1.5 * IQR))]
    print(f"{col}: {len(outliers)} outliers")

df['temperature_celsius'].fillna(df['temperature_celsius'].mean(), inplace=True)
# or median:
df['humidity'] = df['humidity'].fillna(df['humidity'].median())

df['condition_text'].fillna(df['condition_text'].mode()[0], inplace=True)

df['last_updated'] = pd.to_datetime(df['last_updated'])

df.to_csv("Cleaned_GlobalWeatherRepository.csv", index=False)
from google.colab import files
files.download("Cleaned_GlobalWeatherRepository.csv")

df.isnull().sum()         # missing values should be handled
df.duplicated().sum()     # should be 0 after dropping duplicates
df.dtypes                 # confirm conversions (dates, numeric)
df.shape                  # check that you didn't accidentally lose too many rows